# --------------------------------------------- HYDRA -----------------------------------------------------
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:  
    dir: .
# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  save_video : True  # Сохранение итогового видео обработки
  send_info_db : True  # Сохраняем ли инфо в бд (требуется заранее запустить микросервисы если ставите True)
  render_video_flask : True # Отображение результатов обработки видеопотока в веб-интерфейсе (Flask) вместо cv2.imshow
# ------------------------------------------------- NODES --------------------------------------------------
VideoReader:
  src: 0 #test_videos/test_video.mp4  # путь до файла обработки или номер камеры
  skip_secs : 0 # считываем кадры раз в <skip_secs> секунд
  start_timestamp: 0 #начальное время с которого стартуем

PointsDetection:
  max_num_faces : 1
  refine_landmarks : True
  min_detection_confidence : 0.5
  min_tracking_confidence : 0.5
  eye_idxs: {
                    "left": [362, 385, 387, 263, 373, 380],
                    "right": [33, 160, 158, 133, 153, 144],
            }
  ear_tresh: 0.15

show_node:
  scale : 0.7  # Масштабирование итогового окна результатов при imshow=True
  imshow: True  # Нужно ли выводить видео в процессе обработки
  fps_counter_N_frames_stat : 15  # Окно усредения fsp счетчика
  draw_fps_info : True  # Указывать ли fps обработки
  show_coords : True # Отображать ли точки глаз
  show_sleep_status: True # Отображать ли статус сонливости 

Statistic:
  buffer_size: 30 # Время хранения статистик по количеству морганий
  how_often_seconds: 15 

flask_server_video_node:
  host_ip: localhost  # где именно поднять сервис (localhost или "0.0.0.0")
  port: 8000

send_info_db_node:
  time_zone: 0  # базово время в GMT
  table_name: bd  # имя таблицы в БД в которую ведем запись
  drop_prev_table: True  # удалять ли таблицу при перезапуске кода
  memory_safe: True # чистим ли табличные данные с определенным шагом (при True - мы очищаем постепенно БД)
  time_to_clean: 2000000 # период очистки таблицы, указывается в минутах (сколько минут всего храним в БД значения - старее удаляем)
  time_to_check: 1000 #время выполнения функции очистки таблицы, в минутах (с какой частотой заходим в таблицу и чистим все, что больше time_to_clean минут)
  connection_info:  # данные о подключении (должны совпадать со значениями из docker-compose файла)
    user: ml_papa
    password: ml_mama
    host: localhost
    port: 5492  # внутренний порт контейнера с PostgreSQL
    database: db

